# STEM only parameters for v-Cornea simulation https://www.biorxiv.org/content/10.1101/2025.08.11.669602v1
InitSTEM_LambdaSurface=2.0
InitSTEM_TargetSurface=18.0
InitSTEM_LambdaVolume=2.0
InitSTEM_TargetVolume=25.0
DensitySTEM_HalfMaxValue=125
EGF_STEM_HalfMaxValue=3.5
STEM_beta_EGF=1
InitSTEM_LambdaChemo=100.0
EGF_GrowthScalar_STEM=1.0
DensityGrowthScalar_STEM=1.0
SLS_STEMDiffCoef=5.0

InitBASAL_LambdaSurface=2.0
InitBASAL_TargetSurface=20.0
InitBASAL_LambdaVolume=2.0
InitBASAL_TargetVolume=25.0
InitBASAL_LambdaChemo=1000.0
InitBASAL_Division=20000.0
DensityBASAL_HalfMaxValue=125
EGF_BASAL_HalfMaxValue=7.0
BASAL_beta_EGF=1
EGF_GrowthScalar_BASAL=1.0
DensityGrowthScalar_BASAL=1.0
SLS_BASALDiffCoef=5.0

InitWING_LambdaSurface=5.0
InitWING_TargetSurface=25
InitWING_LambdaVolume=2.0
InitWING_TargetVolume=25.0
InitWING_EGFLambdaChemo=20.0
SLS_WINGDiffCoef=5.0

InitSUPER_LambdaSurface=5.0
InitSUPER_TargetSurface=25.0
InitSUPER_LambdaVolume=5.0
InitSUPER_TargetVolume=25.0
EGF_SUPERDiffCoef=20.0
SLS_SUPERDiffCoef=5.0

DeathTimeScalar=1
SLS_MEMBDiffCoef=5.0
SLS_LIMBDiffCoef=5.0
SLS_TEARDiffCoef=5.0
MovementBiasScreteAmount=1
MovementBiasUptake=1
EGF_ScreteAmount=1
EGF_FieldUptakeBASAL=0.0
EGF_FieldUptakeSTEM=0.0
EGF_FieldUptakeSuper=0.0
EGF_FieldUptakeWing=0.0
EGF_GlobalDecay=0.5 # 0.1 from upper bound +0.5
InjuryType=0
IsInjury=False
InjuryTime=200000000
SLS_Injury=False
SLS_Threshold_Method=True
SLS_Threshold=2.0
InjuryX_Center=150
InjuryY_Center=60
InjuryRadius=25
SLS_X_Center                = 100
SLS_Y_Center                = 75
SLS_Concentration           = 2500.0
SLS_Gaussian_pulse = True
LINKWALL_lambda_distance    = 50
LINKWALL_target_distance    = 3
LINKSUPER_lambda_distance   = 50
LINKWALL_target_distance    = 3
LINKWALL_max_distance       = 1000
LINKSUPER_target_distance    = 3
LINKSUPER_max_distance       = 1000
L_max_links_SS              = 5
F_max_links_SS              = 15  
AutoAdjustLinks             = True
GrowthControl=True
MitosisControl=True
DeathControl=True
DifferentiationControl=True
CellCount=True
XHypTracker=False
SloughTracker=False
PressureTracker=True
EGF_SeenByCell=True
SLS_SeenByCell=False
CenterBias=False
DivisionTracker=True
ThicknessPlot=True
VolumeSurfaceDetail=False
SurfactantTracking=True
SnapShot=False
SimTime=50400
